package main.rice.node;

import main.rice.obj.PyCharObj;
import main.rice.obj.PyStringObj;
import java.util.*;

/**
 * A representation of a node for generating PyStringObjs.
 */
public class PyStringNode extends AIterablePyNode<PyStringObj, PyCharObj> {

    /**
     * The domain of characters from which valid strings can be constructed.
     */
    private final String charDomain;

    /**
     * Constructor fot a PyStringNode; initializes its character domain.
     *
     * @param charDomain the valid characters for PyStringObjs generated by this node
     */
    public PyStringNode(String charDomain) {
        this.charDomain = charDomain;
    }

    /**
     * Generates all valid PyStringObjs within the exhaustive domain; begins by generating
     * all valid characters, and then finds all permutations of them of valid length (as
     * constrained by the exhaustive domain).
     *
     * @return a set of PyStringObjs comprising the exhaustive domain
     */
    @Override
    public Set<PyStringObj> genExVals() {
        // Convert charDomain from a String to a list of each individual character
        // in that string
        Set<PyCharObj> innerVals =
                new HashSet<>(new PyStringObj(this.charDomain).getValue());

        // Get all permutations in the form of a list of lists of characters
        return this.genPerms(this.exDomainMax(), innerVals);
    }

    /**
     * Helper function for generating a PyStringObj.
     *
     * @param innerVals the elements to be contained by the generated PyStringObj
     * @return a PyStringObj object encapsulating the innerVals
     */
    @Override
    protected PyStringObj genObj(List<PyCharObj> innerVals) {
        return new PyStringObj(innerVals);
    }

    /**
     * Helper function for generating one random PyCharObj object.
     *
     * @return a randomly-generated object of type PyCharObj from this.charDomain
     */
    @Override
    protected PyCharObj genRandInnerVal() {
        int choice = this.rand.nextInt(this.charDomain.length());
        return new PyCharObj(this.charDomain.charAt(choice));
    }
}