package main.rice.node;

import main.rice.obj.APyObj;
import main.rice.obj.PyTupleObj;

import java.util.List;

/**
 * A representation of a node for generating PyTupleObjs.
 *
 * @param <InnerType> the type of object stored within the lists generated by this node
 */
public class PyTupleNode<InnerType extends APyObj> extends
        AIterablePyNode<PyTupleObj<InnerType>, InnerType> {

    /**
     * Constructor fot a PyTupleNode; stores a reference to its child node (used to
     * generate its contained elements).
     *
     * @param child a node representing the valid elements for this tuple
     */
    public PyTupleNode(APyNode<InnerType> child) {
        this.leftChild = child;
    }

    /**
     * Helper function for generating a PyTupleObj.
     *
     * @param innerVals the elements to be contained by the generated PyTupleObj
     * @return a PyTupleObj object encapsulating the innerVals
     */
    @Override
    protected PyTupleObj<InnerType> genObj(List<InnerType> innerVals) {
        return new PyTupleObj<>(innerVals);
    }
}